// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: xxdb.proto

package xxdb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Query_Type int32

const (
	Query_INSERT Query_Type = 0
	Query_GET    Query_Type = 1
)

// Enum value maps for Query_Type.
var (
	Query_Type_name = map[int32]string{
		0: "INSERT",
		1: "GET",
	}
	Query_Type_value = map[string]int32{
		"INSERT": 0,
		"GET":    1,
	}
)

func (x Query_Type) Enum() *Query_Type {
	p := new(Query_Type)
	*p = x
	return p
}

func (x Query_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Query_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_xxdb_proto_enumTypes[0].Descriptor()
}

func (Query_Type) Type() protoreflect.EnumType {
	return &file_xxdb_proto_enumTypes[0]
}

func (x Query_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Query_Type.Descriptor instead.
func (Query_Type) EnumDescriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{1, 0}
}

type Response_Status int32

const (
	Response_OK           Response_Status = 0
	Response_UNAUTHORIZED Response_Status = 1 // client could't authorized
	Response_CLIENT_ERROR Response_Status = 2
	Response_SERVER_ERROR Response_Status = 3
	Response_OTHER_ERROR  Response_Status = 4
)

// Enum value maps for Response_Status.
var (
	Response_Status_name = map[int32]string{
		0: "OK",
		1: "UNAUTHORIZED",
		2: "CLIENT_ERROR",
		3: "SERVER_ERROR",
		4: "OTHER_ERROR",
	}
	Response_Status_value = map[string]int32{
		"OK":           0,
		"UNAUTHORIZED": 1,
		"CLIENT_ERROR": 2,
		"SERVER_ERROR": 3,
		"OTHER_ERROR":  4,
	}
)

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}

func (x Response_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Response_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_xxdb_proto_enumTypes[1].Descriptor()
}

func (Response_Status) Type() protoreflect.EnumType {
	return &file_xxdb_proto_enumTypes[1]
}

func (x Response_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Response_Status.Descriptor instead.
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{2, 0}
}

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Pass string `protobuf:"bytes,2,opt,name=pass,proto3" json:"pass,omitempty"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xxdb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_xxdb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Auth) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      Query_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=xxdb.Query_Type" json:"type,omitempty"`
	WithMerge bool           `protobuf:"varint,2,opt,name=with_merge,json=withMerge,proto3" json:"with_merge,omitempty"` // merge event with equal device_hash and date_time
	Events    []*Query_Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xxdb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_xxdb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{1}
}

func (x *Query) GetType() Query_Type {
	if x != nil {
		return x.Type
	}
	return Query_INSERT
}

func (x *Query) GetWithMerge() bool {
	if x != nil {
		return x.WithMerge
	}
	return false
}

func (x *Query) GetEvents() []*Query_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status Response_Status   `protobuf:"varint,1,opt,name=status,proto3,enum=xxdb.Response_Status" json:"status,omitempty"`
	Emsg   string            `protobuf:"bytes,2,opt,name=emsg,proto3" json:"emsg,omitempty"` // string with error
	Events []*Response_Event `protobuf:"bytes,3,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xxdb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_xxdb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() Response_Status {
	if x != nil {
		return x.Status
	}
	return Response_OK
}

func (x *Response) GetEmsg() string {
	if x != nil {
		return x.Emsg
	}
	return ""
}

func (x *Response) GetEvents() []*Response_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Query_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceHash int64  `protobuf:"varint,2,opt,name=device_hash,json=deviceHash,proto3" json:"device_hash,omitempty"`
	DeviceDt   uint64 `protobuf:"varint,3,opt,name=device_dt,json=deviceDt,proto3" json:"device_dt,omitempty"` // datetime YYYYMMDDHHMMSS UTC+0
	Hide       bool   `protobuf:"varint,4,opt,name=hide,proto3" json:"hide,omitempty"`                         // hide event fromb user
	Mrn        int64  `protobuf:"varint,5,opt,name=mrn,proto3" json:"mrn,omitempty"`
	Extra      string `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra,omitempty"` // extra fields
}

func (x *Query_Event) Reset() {
	*x = Query_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xxdb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Event) ProtoMessage() {}

func (x *Query_Event) ProtoReflect() protoreflect.Message {
	mi := &file_xxdb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Event.ProtoReflect.Descriptor instead.
func (*Query_Event) Descriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Query_Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Query_Event) GetDeviceHash() int64 {
	if x != nil {
		return x.DeviceHash
	}
	return 0
}

func (x *Query_Event) GetDeviceDt() uint64 {
	if x != nil {
		return x.DeviceDt
	}
	return 0
}

func (x *Query_Event) GetHide() bool {
	if x != nil {
		return x.Hide
	}
	return false
}

func (x *Query_Event) GetMrn() int64 {
	if x != nil {
		return x.Mrn
	}
	return 0
}

func (x *Query_Event) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type Response_Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RawData string          `protobuf:"bytes,2,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	Status  Response_Status `protobuf:"varint,3,opt,name=status,proto3,enum=xxdb.Response_Status" json:"status,omitempty"`
}

func (x *Response_Event) Reset() {
	*x = Response_Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xxdb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response_Event) ProtoMessage() {}

func (x *Response_Event) ProtoReflect() protoreflect.Message {
	mi := &file_xxdb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response_Event.ProtoReflect.Descriptor instead.
func (*Response_Event) Descriptor() ([]byte, []int) {
	return file_xxdb_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Response_Event) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response_Event) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *Response_Event) GetStatus() Response_Status {
	if x != nil {
		return x.Status
	}
	return Response_OK
}

var File_xxdb_proto protoreflect.FileDescriptor

var file_xxdb_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x78, 0x6b, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x78, 0x6b,
	0x64, 0x62, 0x22, 0x2e, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x73, 0x73, 0x22, 0xa8, 0x02, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x78, 0x6b, 0x64,
	0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x77, 0x69, 0x74, 0x68, 0x4d, 0x65, 0x72, 0x67,
	0x65, 0x12, 0x29, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x78, 0x6b, 0x64, 0x62, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x91, 0x01, 0x0a,
	0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x64, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x44, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x04, 0x68, 0x69, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x72, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x72, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x78,
	0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x22, 0x1b, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x4e, 0x53, 0x45,
	0x52, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x01, 0x22, 0xb7, 0x02,
	0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x78, 0x6b, 0x64,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x6d, 0x73, 0x67, 0x12, 0x2c, 0x0a,
	0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x78, 0x6b, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x61, 0x0a, 0x05, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x78, 0x6b, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x57,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x58, 0x2d, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x78, 0x6b, 0x64, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_xxdb_proto_rawDescOnce sync.Once
	file_xxdb_proto_rawDescData = file_xxdb_proto_rawDesc
)

func file_xxdb_proto_rawDescGZIP() []byte {
	file_xxdb_proto_rawDescOnce.Do(func() {
		file_xxdb_proto_rawDescData = protoimpl.X.CompressGZIP(file_xxdb_proto_rawDescData)
	})
	return file_xxdb_proto_rawDescData
}

var file_xxdb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xxdb_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_xxdb_proto_goTypes = []interface{}{
	(Query_Type)(0),        // 0: xxdb.Query.Type
	(Response_Status)(0),   // 1: xxdb.Response.Status
	(*Auth)(nil),           // 2: xxdb.Auth
	(*Query)(nil),          // 3: xxdb.Query
	(*Response)(nil),       // 4: xxdb.Response
	(*Query_Event)(nil),    // 5: xxdb.Query.Event
	(*Response_Event)(nil), // 6: xxdb.Response.Event
}
var file_xxdb_proto_depIdxs = []int32{
	0, // 0: xxdb.Query.type:type_name -> xxdb.Query.Type
	5, // 1: xxdb.Query.events:type_name -> xxdb.Query.Event
	1, // 2: xxdb.Response.status:type_name -> xxdb.Response.Status
	6, // 3: xxdb.Response.events:type_name -> xxdb.Response.Event
	1, // 4: xxdb.Response.Event.status:type_name -> xxdb.Response.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_xxdb_proto_init() }
func file_xxdb_proto_init() {
	if File_xxdb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xxdb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xxdb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xxdb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xxdb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xxdb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response_Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xxdb_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xxdb_proto_goTypes,
		DependencyIndexes: file_xxdb_proto_depIdxs,
		EnumInfos:         file_xxdb_proto_enumTypes,
		MessageInfos:      file_xxdb_proto_msgTypes,
	}.Build()
	File_xxdb_proto = out.File
	file_xxdb_proto_rawDesc = nil
	file_xxdb_proto_goTypes = nil
	file_xxdb_proto_depIdxs = nil
}
